apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-deployment
  labels:
    app: notesapp-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapp-dango
  template:
    metadata:
      labels:
        app: notesapp-django
    spec:
      containers:
      - name: notes-app
        image: sharuquee/notes-app:20
        ports:
        - containerPort: 8000


apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: notesapp-django
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30007
