apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-sharuque
  labels:
    app: notesapp-django
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notesapp-django
  template:
    metadata:
      labels:
        app: notesapp-django
    spec:
      containers:
      - name: notes-app
        image: sharuquee/django:8
        ports:
        - containerPort: 8000
